sudo: false
dist: trusty
language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
install:
  - npm prune
  - npm install
  - lerna exec 'npm install'
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
